Repository duartels/tech-challenge-01, pull requests merged in 2025-01, with the labels that each got.

#2 Feature/create backend
  .eslintignore
  .eslintrc.json
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc
  commitlint.config.js
  package-lock.json
  package.json
  src/app/api/transaction/route.ts
  src/app/page.tsx
  src/components/Select/index.tsx
  src/constants/transaction.ts
  src/data-access/application/index.ts
  src/data-access/application/storage.facade.ts
  src/data-access/application/transaction.facade.ts
  src/data-access/index.ts
  src/data-access/infrastructure/index.ts
  src/data-access/infrastructure/storage.repository.ts
  src/data-access/infrastructure/transaction.repository.ts
  src/data-source/application/index.ts
  src/data-source/application/transaction-source.facade.ts
  src/data-source/index.ts
  src/data-source/infrastructure/index.ts
  src/data-source/infrastructure/transaction-source.repository.ts
  src/domain/application/index.ts
  src/domain/application/storage.abs.facade.ts
  src/domain/application/transaction.abs.facade.ts
  src/domain/enums/index.ts
  src/domain/enums/transaction-label.enum.ts
  src/domain/enums/transaction-value.enum.ts
  src/domain/index.ts
  src/domain/infrastructure/index.ts
  src/domain/infrastructure/storage.abs.repository.ts
  src/domain/infrastructure/transaction.abs.repository.ts
  src/domain/types/index.ts
  src/domain/types/option.type.ts
  src/domain/types/select-props.type.ts
  src/domain/types/storage.interface.ts
  src/domain/types/transaction.interface.ts
  src/hooks/index.ts
  src/hooks/useValidateAndSyncData.ts
  tsconfig.json
Labels: enhancement

#5 Feature/crud-transaction
  .eslintrc.json
  src/app/api/transaction/route.ts
  src/app/page.tsx
  src/components/Button/index.tsx
  src/components/Input/index.tsx
  src/components/Select/index.tsx
  src/components/index.ts
  src/data-access/application/index.ts
  src/data-access/application/transaction.facade.ts
  src/data-access/infrastructure/index.ts
  src/data-access/infrastructure/storage.repository.ts
  src/data-access/infrastructure/transaction.repository.ts
  src/data-source/application/transaction-source.facade.ts
  src/data-source/infrastructure/transaction-source.repository.ts
  src/domain/application/index.ts
  src/domain/application/storage.abs.facade.ts
  src/domain/application/transaction.abs.facade.ts
  src/domain/dtos/create-transaction.dto.ts
  src/domain/dtos/index.ts
  src/domain/index.ts
  src/domain/infrastructure/index.ts
  src/domain/infrastructure/storage.abs.repository.ts
  src/domain/infrastructure/transaction.abs.repository.ts
  src/domain/types/select-props.type.ts
  src/hooks/index.ts
  src/hooks/useTransaction.ts
  tsconfig.json
Labels: bug, enhancement

#4 feat: create overview
  .eslintignore
  .eslintrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  public/.gitkeep
  public/icons/overview-bottom-mobile.svg
  public/icons/overview-bottom.svg
  public/icons/overview-money.svg
  public/icons/overview-top-mobile.svg
  public/icons/overview-top.svg
  src/app/page.tsx
  src/components/Overview/Overview.stories.ts
  src/components/Overview/index.tsx
  src/domain/dtos/create-transaction.dto.ts
  src/domain/types/index.ts
  src/domain/types/overview.type.ts
Labels: enhancement

#13 fix: changes body to save `transactions`
  src/data-access/infrastructure/transaction.repository.ts
Labels: bug
